# ===========================
# Spring Configuration
# ===========================
spring:
  datasource:
#<<<<<<< Updated upstream
#    url: jdbc:postgresql://145.223.19.160:5432/nearprop_user?currentSchema=public
#=======
    url: jdbc:postgresql://145.223.19.160:5432/nearprop_user
#>>>>>>> Stashed changes
    username: nearprop_user
    password: " Nearprop#2025"

  jpa:
    hibernate:
      ddl-auto: none   # disable schema validation

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# ===========================
# Application Settings
# ===========================
app:
  email:
    enabled: ${EMAIL_ENABLED:true}
  url: ${APP_URL:http://localhost:8080}

# ===========================
# Digital SMS API Configuration
# ===========================
digital-sms:
  api-key: ${DIGITAL_SMS_API_KEY:Bearer 258|uEXsqSmGr4BfCR1NyUTmYx0hAhmkBTw6MeRbdqcr1f13f0a9}
  sender-id: ${DIGITAL_SMS_SENDER_ID:RWTLTD}
  entity-id: ${DIGITAL_SMS_ENTITY_ID:1701175100042384521}
  template-id: ${DIGITAL_SMS_TEMPLATE_ID:1707175170423044409}
  api-url: ${DIGITAL_SMS_API_URL:https://sms.digitalsms.net/api/v3/sendsms}
  balance-url: ${DIGITAL_SMS_BALANCE_URL:https://sms.digitalsms.net/api/v3/me}
  low-balance-threshold: ${DIGITAL_SMS_LOW_BALANCE_THRESHOLD:500}
  notification-emails: ${DIGITAL_SMS_NOTIFICATION_EMAILS:rudraashwitechnology@gmail.com,mail.rudraashwitechnology@gmail.com}

# ===========================
# AWS Configuration
# ===========================
aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    reelsBucket: ${AWS_S3_REELS_BUCKET}
    reelsFolder: ${AWS_S3_REELS_FOLDER:media/reels}
    thumbnailsFolder: ${AWS_S3_THUMBNAILS_FOLDER:media/thumbnails}
    profileFolder: ${AWS_S3_PROFILE_FOLDER:media/profiles}
    propertyFolder: ${AWS_S3_PROPERTY_FOLDER:media/properties}

# ===========================
# JWT Secret
# ===========================
jwt:
  secret: ${JWT_SECRET:sandeep_kushwaha_application_developer_2025_of_nearprop_acoreithub_pvt_ltd_ratanlok_colony_schem_no}

# ===========================
# Google Maps
# ===========================
google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

# ===========================
# Razorpay Configuration
# ===========================
payment:
  gateway:
    razorpay:
      key: ${RAZORPAY_KEY}
      secret: ${RAZORPAY_SECRET}
      api:
        url: ${RAZORPAY_API_URL:https://api.razorpay.com/v1}

# ===========================
# Reel Pricing
# ===========================
reels:
  price: ${REELS_PRICE:99.00}



server:
  address: 0.0.0.0
  port: 8080
