-- Add permanentId column to users table
ALTER TABLE users
ADD COLUMN permanent_id VARCHAR(255) UNIQUE;

-- Generate permanent IDs for existing users 
-- This will be a placeholder, actual IDs will be properly generated by the application for new users
UPDATE users u
SET permanent_id = CONCAT(
    CASE 
        WHEN EXISTS (SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id AND ur.role = 'SELLER') THEN 'RANPS'
        WHEN EXISTS (SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id AND ur.role = 'ADVISOR') THEN 'RANPPA'
        WHEN EXISTS (SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id AND ur.role = 'DEVELOPER') THEN 'RANPD'
        ELSE 'RANPU'
    END,
    DATE_FORMAT(NOW(), '%Y%m%d'),
    u.id
)
WHERE permanent_id IS NULL;

-- Add permanent ID column to properties table
ALTER TABLE properties
ADD COLUMN permanent_id VARCHAR(255) UNIQUE;

-- Generate permanent IDs for existing properties
UPDATE properties p
SET permanent_id = CONCAT('RANP', DATE_FORMAT(NOW(), '%Y%m%d'), p.id)
WHERE permanent_id IS NULL;

-- Add new columns to properties table
ALTER TABLE properties
ADD COLUMN owner_permanent_id VARCHAR(255),
ADD COLUMN added_by_user_id BIGINT,
ADD COLUMN added_by_franchisee BOOLEAN DEFAULT FALSE,
ADD CONSTRAINT fk_property_added_by FOREIGN KEY (added_by_user_id) REFERENCES users(id);

-- Update owner_permanent_id for existing properties
UPDATE properties p
JOIN users u ON p.owner_id = u.id
SET p.owner_permanent_id = u.permanent_id
WHERE p.owner_permanent_id IS NULL AND u.permanent_id IS NOT NULL; 